version: '3'

services:

  # ApiGatewayService
  gateway:
    build:
      context: ./ApiGatewayService
      dockerfile: ./Dockerfile
    image: eminarikan/gateway:${TAG_VERSION}
    container_name: gateway

  # AuthMicroService
  auth:
    build:
      context: ./AuthMicroService
      dockerfile: ./Dockerfile
    image: eminarikan/auth:${TAG_VERSION}
    container_name: auth

  # UserMicroService
  user:
    build:
      context: ./UserMicroService
      dockerfile: ./Dockerfile
    image: eminarikan/user:${TAG_VERSION}
    container_name: user

  # CardMicroService
  card:
    build:
      context: ./CardMicroService
      dockerfile: ./Dockerfile
    image: eminarikan/card:${TAG_VERSION}
    container_name: card

  # MailService
  mail:
    build:
      context: ./MailService
      dockerfile: ./Dockerfile
    image: eminarikan/mail:${TAG_VERSION}
    container_name: mail