server:
  port: 8085
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: http://localhost:4040
          predicates:
            - Path=/api/v1/auth/**
        - id: USER-SERVICE
          uri: http://localhost:4041
          predicates:
            - Path=/user/**
        - id: CARD-SERVICE
          uri: http://localhost:4042
          predicates:
            - Path=/card/**
        - id: MAIL-SERVICE
          uri: http://localhost:4043
          predicates:
            - Path=/mail/**
