version: '3'
services:

  # ApiGatewayService
  gateway:
    image: eminarikan/gateway:v0.3
    container_name: gateway
    ports:
      - "80:80"

  # AuthMicroService
  auth:
    image: eminarikan/auth:v0.3
    container_name: auth
    ports:
      - "4040:4040"

  # UserMicroService
  user:
    image: eminarikan/user:v0.3
    container_name: user
    ports:
      - "4041:4041"

  # CardMicroService
  card:
    image: eminarikan/card:v0.3
    container_name: card
    ports:
      - "4042:4042"

  # MailService
  mail:
    image: eminarikan/mail:v0.3
    container_name: mail
    ports:
      - "4043:4043"