server:
  port: 4041
spring:
  data:
    mongodb:
      host: localhost
      port: 27020
      username: studentcarduser
      password: root
      database: studentcard
base-api:
  url: http://10.39.80.53:80