server:
  port: 4041
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: root
  data:
    mongodb:
      host: mongo
      port: 27017
      username: studentcarduser
      password: root
      database: studentcard
base-api:
  url: http://10.39.80.53:80

rabbitmq:
  getStudentQueue: student-queue