server:
  port: 4042
spring:
  rabbitmq:
      host: localhost
      port: 5672
      username: user
      password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      username: studentcarduser
      password: root
      database: studentcard
base-api:
  url: http://localhost:8081
user-service:
  url: http://localhost:4041/api/v1/user

rabbitmq:
  getUserBindingKey: get-user-binging-key
  getUserQueue: user-queue