server:
  port: 4042
spring:
  rabbitmq:
      host: rabbitmq
      port: 5672
      username: user
      password: root
  data:
    mongodb:
      host: mongo
      port: 27020
      username: studentcarduser
      password: root
      database: studentcard
base-api:
  url: http://localhost:80