server:
  port: 4042
spring:
  rabbitmq:
      host: rabbitmq
      port: 5672
      username: user
      password: root
  data:
    mongodb:
      host: mongo
      port: 27017
      username: studentcarduser
      password: root
      database: studentcard
base-api:
  url: http://localhost:80
student-service:
  url: http://student:4041/api/v1/student

rabbitmq:
  getStudentBindingKey: get-student-binging-key
  getStudentQueue: student-queue