server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - OPTIONS
      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}
      routes:
        #Auth service routes
        - id: auth-service
          uri: http://localhost:4040
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth-service-application
                fallbackUri: forward:/fallback/auth
        - id: secretKey-service
          uri: http://localhost:4040
          predicates:
            - Path=/auth/secret-key/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth-service-application
                fallbackUri: forward:/fallback/auth/secret-key
         #User service route
        - id: user-service
          uri: http://localhost:4041
          predicates:
            - Path=/user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user-service-application
                fallbackUri: forward:/fallback/user
        - id: mainGroup-service
          uri: http://localhost:4041
          predicates:
            - Path=/user/main-group/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: user-service-application
                fallbackUri: forward:/fallback/user/main-group
        #Mail service route
        - id: mail-service
          uri: http://localhost:4043
          predicates:
            - Path=/mail/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: mail-service-application
                fallbackUri: forward:/fallback/mail
          #Card service routes
        - id: card-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card
        - id: absence-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/absence/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/absence
        - id: algorithm-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/algorithm/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/algorithm
        - id: application-process-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/application-process/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/application-process
        - id: assignment-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/assignment/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/assignment
        - id: attendance-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/attendance/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/attendance
        - id: group-student-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/group-student/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/group-student
        - id: card-parameter-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/card-parameter/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/card-parameter
        - id: career-education-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/career-education/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/career-education
        - id: contribution-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/contribution/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/contribution
        - id: document-submit-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/document-submit/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/document-submit
        - id: employment-interview-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/employment-interview/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/employment-interview
        - id: exam-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/exam/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/exam
        - id: graduation-project-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/graduation-project/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/graduation-project
        - id: internship-group-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/internship-group/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/internship-group
        - id: internship-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/internship/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/internship
        - id: internship-tasks-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/internship-tasks/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/internship-tasks
        - id: interview-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/interview/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/interview
        - id: personal-motivation-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/personal-motivation/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/personal-motivation
        - id: project-behavior-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/project-behavior/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/project-behavior
        - id: project-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/project/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/project
        - id: rollcall-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/rollcall/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/rollcall
        - id: team-lead-assessment-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/team-lead-assessment/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/team-lead-assessment
        - id: teamwork-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/teamwork/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/teamwork
        - id: technical-interview-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/technical-interview/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/technical-interview
        - id: trainer-assessment-coefficients-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/trainer-assessment-coefficients/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/trainer-assessment-coefficients
        - id: trainer-assessment-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/trainer-assessment/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/trainer-assessment
        - id: transcript-default-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/transcript-default/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/transcript-default
        - id: written-exam-service
          uri: http://localhost:4042
          predicates:
            - Path=/card/written-exam/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card/written-exam


