server:
  port: 443
  ssl:
    key-store: ${KEYSTORE_JKS_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}
      routes:
        #Auth service routes
        - id: auth-service
          uri: http://auth:4040
          predicates:
            - Path=/auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: auth-service-application
                fallbackUri: forward:/fallback/auth
         #Student service route
        - id: student-service
          uri: http://student:4041
          predicates:
            - Path=/student/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: student-service-application
                fallbackUri: forward:/fallback/student
        #Mail service route
        - id: mail-service
          uri: http://mail:4043
          predicates:
            - Path=/mail/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: mail-service-application
                fallbackUri: forward:/fallback/mail
          #Card service routes
        - id: card-service
          uri: http://card:4042
          predicates:
            - Path=/card/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                name: card-service-application
                fallbackUri: forward:/fallback/card