server:
  port: 4040
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      username: studentcarduser
      password: root
      database: studentcard

rabbitmq:
  queueActivationLink: activation-link-mail-queue
  activationLinkBindingKey: activation-link-binding-key
  registerStudentAndTrainerBindingKey: register-student-and-trainer-binding-key
  registerStudentAndTrainerQueue: register-student-and-trainer-queue
  authDirectExchange: auth-direct-exchange

passwords:
  admin: ${ADMIN_PWD:1243}
  workshop: ${WORKSHOP_PWD:1243}
  education: ${EDUCATION_PWD:1243}
  internship: ${INTERNSHIP_PWD:1243}
  employment: ${EMPLOYMENT_PWD:1243}